### ISSUE TITLE
Proporcionar texto para traducir (en inglés y ruso)

### ISSUE THREAD

**Issue by Andredron** [CharlieFuu69/RenPy_RhythmBeats#1]
Buenas tardes, por favor, facilítenos un texto para traducir su proyecto al ruso y al inglés. (Por supuesto que no tengo ningún problema en conseguir el texto yo mismo, pero educadamente debería pedir permiso al autor del proyecto). Le estaré muy agradecido.

Good afternoon, please provide a text to translate your project into Russian and English. (Of course I have no problem getting the text myself, but politely I should ask permission from the author of the project). I will be very grateful to you.

**Comment by CharlieFuu69** [comment]
Hello!
I have no problem with you wanting to translate the content of Ren'Py RhythmBeats! On the contrary, I'm glad you want to.
At the moment I have some pending because I have modified some parts of the module (I am rewriting it from .py to .rpym), which will lead me to eventually update some parts of the Ren'Py RhythmBeats documentation! =(

If you wish, you can fork this repository and translate the content of this repository, but you should be aware of any significant changes in the documentation.
Any changes you want to make, attach the main repository. I would really appreciate it :3

**Comment by CharlieFuu69** [comment]
This Issue will be closed as it is considered as **"Fixed"**. If you have other problems, feel free to create a new Issue =D

**Comment by Andredron** [comment]
Tipo de traducción Inglés y ruso prescrito, el menú principal, la información sobre los álbumes de música fue bien, pero parece que metí la pata en alguna parte y cuando se inicia un nuevo juego aparece un error, después de ignorar el error, juega animación, va puntuación y el juego termina con la salida al menú principal.

los archivos donde prescribí los cambios aquí https://github.com/Andredron/RenPy_RhythmBeats-Test-/tree/main/EDIT_FILES

**Comment by CharlieFuu69** [comment]
> Tipo de traducción Inglés y ruso prescrito, el menú principal, la información sobre los álbumes de música fue bien, pero parece que metí la pata en alguna parte y cuando se inicia un nuevo juego aparece un error, después de ignorar el error, juega animación, va puntuación y el juego termina con la salida al menú principal.
> 
> los archivos donde prescribí los cambios aquí https://github.com/Andredron/RenPy_RhythmBeats-Test-/tree/main/EDIT_FILES

@Andredron Can you show me a screenshot of the exceptions?
If you modify only the strings with information, and not the strings used to jump to labels or dictionary keys, you shouldn't have any problems...
