### ISSUE TITLE
Volver a descargar archivos

### ISSUE THREAD

**Issue by Andredron** [CharlieFuu69/RenPy_RhythmBeats#2]
Mientras traducía el proyecto me di cuenta de un error, cuando se borran los datos permanentes (a través del Renpe Launcher) o cuando se borra la carpeta de datos del juego en el PC C:\Documents and Settings\Admin\Application Data\RenPy y se inicia el proyecto de nuevo, vuelve a descargar los archivos sin comprobar si se han guardado antes.
![Снимок экрана (49)](https://user-images.githubusercontent.com/55322207/220952418-7e3c4672-f022-4853-8963-bc728bc627a3.png)
![Снимок экрана (48)](https://user-images.githubusercontent.com/55322207/220952482-ba4799a6-e098-4a87-9d71-6bc75c849960.png)

**Comment by CharlieFuu69** [comment]
If you have the game already unpacked, and you are using the Ren'Py Launcher, try doing the following:

![image](https://user-images.githubusercontent.com/77955772/220981558-6e0f578e-18be-4920-bacc-e24c3c3ce807.png)

When you run the project in Ren'Py, it automatically runs with the `config.developer` flag set to `True`.

Try modifying the following labels so that the game bypasses the download verification process:

* Label `check_updates`, Line `19` (File `main_sequence.rpy`)
* Label `main_menu`, Line `39` (File `main_sequence.rpy`)

Adding the `if not config.developer` conditional will make you skip that process and immediately enter the track menu :3

I hope I've helped =)
